
version: "3"

services:
  shuffle-frontend:
    image: ghcr.io/shuffle/shuffle-frontend:latest   
    ports:
      - "3443:3443"
    depends_on:
      - shuffle-backend

  shuffle-backend:
    image: ghcr.io/shuffle/shuffle-backend:latest    
    depends_on:
      - opensearch

  shuffle-orborus:
    image: ghcr.io/shuffle/shuffle-orborus:latest     

  opensearch:
    image: opensearchproject/opensearch:latest      

  thehive:
    image: thehiveproject/thehive:latest
    ports:
      - "9000:9000"
